name: multiple python versions

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
    - name: Build extensions
      run: |
        python -m setup build_ext --inplace
    - name: Test scripts
      run: |
        python -m pgmmvdec.script -q res
    - name: Test package
      run: |
        pip install .
        pgmmvdec -q res
