name: validate package

on:
  push: { branches: ['**'] }
  pull_request: {}

jobs:
  validate-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build inplace
      run: |
        pip install --upgrade pip
        pip install -e .
    - name: Run test scripts
      run: |
        python -m tests.test_cbc
        python -m tests.test_decrypt
        python -m tests.test_pgmmv
    - name: Run command line script
      run: |
        pgmmvdec -q tests/samples
